name: Deploy

#will dispatch the deploy when active manually (workflow_dispatch) or by push on the branches bellow
on:
  workflow_dispatch:
  push:
    branches: [main, stage]
  
jobs:
  deploy-test:
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-test
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: docker-compose build
      - run: docker-compose up -d
      - name: Docker Hub login
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      - name: Push to Docker Hub backend image
        run: docker push guganl/backend-sorteios
      #- name: Push to Docker Hub mysql image
      #  run: docker push mysql:8.0
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-production
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: docker-compose build
      - run: docker-compose up -d
      - name: Docker Hub login
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      - name: Push to Docker Hub backend image
        run: docker push guganl/backend-sorteios
      #- name: Push to Docker Hub mysql image
      #  run: docker push mysql:8.0